version: '3'
services:
  frontend:
    build:
      context: ./frontend
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - ./frontend:/app:rw
      # - /app/node_modules
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
  backend:
    build:
      context: ./backend
      args:
        USER_ID: ${UID:-1000}
        GROUP_ID: ${GID:-1000}
    volumes:
      - ./backend:/app
      - ${PDF_FOLDER:-./pdf}:/pdf
    ports:
      - "5000:5000"
      - "8899:8888"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    shm_size: '6g'  # Increase shared memory to 6GB
